# Generated by Django 4.1.4 on 2022-12-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_io', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataio',
            name='file',
        ),
        migrations.RemoveField(
            model_name='dataio',
            name='file_type',
        ),
        migrations.AddField(
            model_name='dataio',
            name='file_link',
            field=models.URLField(default=''),
        ),
    ]
