# Generated by Django 4.1.4 on 2022-12-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_io', '0002_remove_dataio_file_remove_dataio_file_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[('Monday', 'Shift is on Mondays'), ('Tuesday', 'Shift is on Tuesdays'), ('Wednesday', 'Shift is on Wednesdays'), ('Thursday', 'Shift is on Thursdays'), ('Friday', 'Shift is on Fridays')], max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
    ]
