# Generated by Django 4.1.4 on 2022-12-29 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_io', '0003_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emplid', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('shifts', models.ManyToManyField(to='data_io.shift')),
            ],
        ),
    ]
