# Generated by Django 4.1.4 on 2022-12-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_io', '0005_remove_uta_name_uta_firstname_uta_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
