# Generated by Django 4.1.4 on 2022-12-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_io', '0006_randompass'),
    ]

    operations = [
        migrations.AddField(
            model_name='randompass',
            name='random_pass',
            field=models.CharField(default='', max_length=100),
        ),
    ]
