# Generated by Django 4.1.4 on 2023-01-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_io', '0008_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='number_of_shifts',
            field=models.IntegerField(default=1),
        ),
    ]
